"""
QuantForge Trade Diagnostic
===========================

Purpose:
    Diagnose the actual signals generated by an individual strategy.

Current focus:
    17_ny_orb_breakout

Run from project root:

    python scripts/diagnose_trades.py
"""

from __future__ import annotations

# =============================================================================
# PROJECT PATH
# =============================================================================

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# =============================================================================
# IMPORTS
# =============================================================================

import importlib.util

import pandas as pd

from engine.data import load_csv


# =============================================================================
# CONFIGURATION
# =============================================================================

DATA_PATH = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "fiveminutes"
    / "xauusd_5m.csv"
)

STRATEGY_PATH = (
    PROJECT_ROOT
    / "strategies"
    / "17_ny_orb_breakout.py"
)

MAX_SIGNALS_TO_DISPLAY = 30


# =============================================================================
# HELPERS
# =============================================================================

def print_header(title: str) -> None:
    print()
    print("=" * 90)
    print(title)
    print("=" * 90)


def print_section(title: str) -> None:
    print()
    print("-" * 90)
    print(title)
    print("-" * 90)


def load_strategy(path: Path):
    """
    Dynamically load a strategy Python file.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Strategy file not found:\n{path}"
        )

    spec = importlib.util.spec_from_file_location(
        "diagnostic_strategy",
        path,
    )

    if spec is None or spec.loader is None:
        raise ImportError(
            f"Could not create import specification for:\n{path}"
        )

    module = importlib.util.module_from_spec(spec)

    spec.loader.exec_module(module)

    if not hasattr(module, "generate_signals"):
        raise AttributeError(
            f"{path.name} does not define generate_signals(df)"
        )

    return module


# =============================================================================
# MAIN
# =============================================================================

def main() -> None:

    print_header("QUANTFORGE TRADE DIAGNOSTIC")

    print(f"Project root : {PROJECT_ROOT}")
    print(f"Dataset      : {DATA_PATH}")
    print(f"Strategy     : {STRATEGY_PATH}")

    # =========================================================================
    # 1. CHECK FILES
    # =========================================================================

    print_section("1. FILE CHECK")

    if not DATA_PATH.exists():
        print("❌ Dataset not found.")
        print(DATA_PATH)
        return

    print("✅ Dataset found.")

    if not STRATEGY_PATH.exists():
        print("❌ Strategy not found.")
        print(STRATEGY_PATH)
        return

    print("✅ Strategy found.")

    # =========================================================================
    # 2. LOAD DATA
    # =========================================================================

    print_section("2. LOAD DATA")

    try:
        df = load_csv(DATA_PATH)
    except Exception as exc:
        print("❌ Failed to load data.")
        print()
        print(repr(exc))
        return

    print("✅ Data loaded.")

    print()
    print(f"Rows      : {len(df):,}")
    print(f"Columns   : {list(df.columns)}")

    print()

    if len(df) > 0:
        print(f"First row : {df.index[0]}")
        print(f"Last row  : {df.index[-1]}")

    # =========================================================================
    # 3. LOAD STRATEGY
    # =========================================================================

    print_section("3. LOAD STRATEGY")

    try:
        strategy = load_strategy(STRATEGY_PATH)
    except Exception as exc:
        print("❌ Failed to load strategy.")
        print()
        print(repr(exc))
        return

    print("✅ Strategy loaded.")
    print(f"Function  : {strategy.generate_signals}")

    # =========================================================================
    # 4. GENERATE SIGNALS
    # =========================================================================

    print_section("4. GENERATE SIGNALS")

    try:
        signals = strategy.generate_signals(df)
    except Exception as exc:
        print("❌ Strategy failed while generating signals.")
        print()
        print(repr(exc))
        return

    print("✅ Signals generated.")

    # =========================================================================
    # 5. BASIC SIGNAL VALIDATION
    # =========================================================================

    print_section("5. SIGNAL VALIDATION")

    print(f"Data rows     : {len(df):,}")
    print(f"Signal rows   : {len(signals):,}")

    index_equal = signals.index.equals(df.index)

    print(f"Index equal   : {index_equal}")

    if not index_equal:
        print()
        print("❌ SIGNAL INDEX DOES NOT MATCH DATA INDEX.")

        print()
        print("Data index sample:")
        print(df.index[:5])

        print()
        print("Signal index sample:")
        print(signals.index[:5])

        return

    print("✅ Signal index matches data index.")

    # =========================================================================
    # 6. SIGNAL TYPE / NaN CHECK
    # =========================================================================

    print_section("6. SIGNAL VALUES")

    print(f"Signal dtype  : {signals.dtype}")
    print(f"NaN count     : {signals.isna().sum():,}")

    numeric_signals = pd.to_numeric(
        signals,
        errors="coerce",
    )

    invalid_numeric = numeric_signals.isna().sum()

    print(f"Non-numeric   : {invalid_numeric:,}")

    if invalid_numeric:
        print("❌ Non-numeric signal values detected.")
        return

    unique_values = sorted(
        pd.Series(numeric_signals.unique()).tolist()
    )

    print()
    print("Unique signal values:")
    print(unique_values[:50])

    # =========================================================================
    # 7. POSITION DISTRIBUTION
    # =========================================================================

    print_section("7. POSITION DISTRIBUTION")

    long_count = (numeric_signals > 0).sum()
    short_count = (numeric_signals < 0).sum()
    flat_count = (numeric_signals == 0).sum()

    print(f"LONG bars      : {long_count:,}")
    print(f"SHORT bars     : {short_count:,}")
    print(f"FLAT bars      : {flat_count:,}")
    print(f"TOTAL bars     : {len(numeric_signals):,}")

    # =========================================================================
    # 8. SIGNAL CHANGE EVENTS
    # =========================================================================

    print_section("8. SIGNAL CHANGE EVENTS")

    previous = numeric_signals.shift(1).fillna(0)

    changes = numeric_signals != previous

    change_events = pd.DataFrame(
        {
            "signal": numeric_signals[changes],
            "previous": previous[changes],
        }
    )

    print(
        f"Signal change events : "
        f"{len(change_events):,}"
    )

    # =========================================================================
    # 9. ACTUAL NON-ZERO SIGNALS
    # =========================================================================

    print_section("9. NON-ZERO SIGNALS")

    non_zero = numeric_signals != 0

    signal_events = pd.DataFrame(
        {
            "timestamp": df.index[non_zero],
            "signal": numeric_signals[non_zero].values,
            "open": df.loc[non_zero, "open"].values,
            "high": df.loc[non_zero, "high"].values,
            "low": df.loc[non_zero, "low"].values,
            "close": df.loc[non_zero, "close"].values,
        }
    )

    print(
        f"Total non-zero signal bars : "
        f"{len(signal_events):,}"
    )

    if signal_events.empty:
        print()
        print("❌ ZERO NON-ZERO SIGNALS.")
        print()
        print(
            "This confirms that the strategy itself "
            "is returning no trades."
        )
    else:

        print()
        print(
            signal_events
            .head(MAX_SIGNALS_TO_DISPLAY)
            .to_string(index=False)
        )

    # =========================================================================
    # 10. SIGNAL ENTRY EVENTS
    # =========================================================================

    print_section("10. ENTRY EVENTS")

    # A position entry occurs when:
    #
    # 0 -> +1
    # 0 -> -1
    # -1 -> +1
    # +1 -> -1

    entry_mask = (
        (numeric_signals != 0)
        & (
            (previous == 0)
            | (numeric_signals != previous)
        )
    )

    entries = pd.DataFrame(
        {
            "timestamp": df.index[entry_mask],
            "signal": numeric_signals[entry_mask].values,
            "open": df.loc[entry_mask, "open"].values,
            "high": df.loc[entry_mask, "high"].values,
            "low": df.loc[entry_mask, "low"].values,
            "close": df.loc[entry_mask, "close"].values,
        }
    )

    print(f"Entry events : {len(entries):,}")

    if not entries.empty:
        print()
        print(
            entries
            .head(MAX_SIGNALS_TO_DISPLAY)
            .to_string(index=False)
        )

    # =========================================================================
    # 11. ONE-TRADE-PER-DAY CHECK
    # =========================================================================

    print_section("11. DAILY SIGNAL CHECK")

    if not entries.empty:

        entry_times = pd.to_datetime(
            entries["timestamp"]
        )

        # Convert to New York if timezone-aware.
        if entry_times.dt.tz is not None:
            entry_ny = entry_times.dt.tz_convert(
                "America/New_York"
            )
        else:
            entry_ny = entry_times

        entries["_ny_date"] = entry_ny.dt.date
        entries["_ny_time"] = entry_ny.dt.strftime("%H:%M")

        daily_counts = (
            entries
            .groupby("_ny_date")
            .size()
        )

        print(
            f"Days with entries : "
            f"{len(daily_counts):,}"
        )

        print(
            f"Maximum entries in one day : "
            f"{daily_counts.max()}"
        )

        multiple_entries = daily_counts[
            daily_counts > 1
        ]

        print(
            f"Days with multiple entries : "
            f"{len(multiple_entries):,}"
        )

        if not multiple_entries.empty:

            print()
            print("Example days with multiple entries:")

            print(
                multiple_entries
                .head(20)
                .to_string()
            )

    else:
        print("No entries to analyze.")

    # =========================================================================
    # 12. LONG / SHORT ENTRY COUNTS
    # =========================================================================

    print_section("12. LONG / SHORT ENTRY COUNTS")

    if not entries.empty:

        long_entries = (
            entries["signal"] > 0
        ).sum()

        short_entries = (
            entries["signal"] < 0
        ).sum()

        print(f"LONG entries  : {long_entries:,}")
        print(f"SHORT entries : {short_entries:,}")

    else:

        print("LONG entries  : 0")
        print("SHORT entries : 0")

    # =========================================================================
    # 13. SIGNAL TIME DISTRIBUTION
    # =========================================================================

    print_section("13. SIGNAL TIME DISTRIBUTION")

    if not entries.empty:

        time_distribution = (
            entries
            .groupby("_ny_time")
            .size()
            .sort_values(ascending=False)
            .head(30)
        )

        print(
            time_distribution
            .to_string()
        )

    else:

        print("No signal times available.")

    # =========================================================================
    # 14. FINAL DIAGNOSIS
    # =========================================================================

    print_header("FINAL DIAGNOSIS")

    print(f"Data bars              : {len(df):,}")
    print(f"Signal bars            : {len(signals):,}")
    print(f"LONG bars              : {long_count:,}")
    print(f"SHORT bars             : {short_count:,}")
    print(f"Non-zero signal bars   : {len(signal_events):,}")
    print(f"Entry events           : {len(entries):,}")

    print()

    if len(signal_events) == 0:

        print("❌ STRATEGY PRODUCES ZERO SIGNALS.")

        print()
        print(
            "The problem is inside the ORB strategy "
            "or its ORB detection logic."
        )

    else:

        print("✅ STRATEGY PRODUCES SIGNALS.")

        print()
        print(
            "The next investigation should compare "
            "these signals against the engine's execution."
        )

    print()
    print("=" * 90)
    print("DIAGNOSTIC COMPLETE")
    print("=" * 90)


# =============================================================================
# ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    main()